robot_radius: 0.17 

# 膨脹層設定
inflation_layer:
  enabled: true
  cost_scaling_factor: 3.0
  inflation_radius: 0.02

# 障礙物層設定
obstacle_layer:
  enabled: true
  obstacle_range: 2.5
  raytrace_range: 3.0
  observation_sources: laser_scan_sensor
  laser_scan_sensor:
    sensor_frame: laser_link
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true