robot_radius: 0.17

# 膨脹層設定
inflation_layer:
  enabled: true
  cost_scaling_factor: 10.0
  inflation_radius: 0.25

# 障礙物層設定
obstacle_layer:
  enabled: true
  obstacle_range: 1.0
  raytrace_range: 1.5
  observation_sources: laser_scan_sensor
  laser_scan_sensor:
    sensor_frame: laser_link
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true