DWAPlannerROS:
  # Robot Configuration Parameters
  acc_lim_x: 2.0
  acc_lim_y: 0.0
  acc_lim_theta: 3.2
  max_vel_x: 1.0
  min_vel_x: -1.0
  max_vel_theta: 2.5
  min_vel_theta: -2.5
  clearing_rotation_allowed: true

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 1.3
  
  # Forward Simulation Parameters
  sim_time: 2.0
  
  # Trajectory Scoring Parameters
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.05
  
  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

  # Debug
  publish_cost_grid: true