DWAPlannerROS:
  # Robot Configuration
  acc_lim_x: 2.0
  acc_lim_y: 0.0
  acc_lim_theta: 3.2
  max_vel_x: 0.8
  min_vel_x: -0.25
  max_vel_theta: 2.0
  min_vel_theta: -2.0

  # Goal Tolerance
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.15
  
  # Forward Simulation
  sim_time: 1.7
  
  # Trajectory Scoring
  path_distance_bias: 10.0
  goal_distance_bias: 0.01
  occdist_scale: 10.0
  forward_point_distance: 0.6
  
  # Oscillation Prevention
  oscillation_reset_dist: 0.05
  
  publish_cost_grid: true