DWAPlannerROS:
  # Robot Configuration Parameters
  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.2
  max_vel_x: 1.5
  min_vel_x: 0.1
  max_vel_theta: 0.4
  min_vel_theta: 0.1

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.2
  
  # Forward Simulation Parameters
  sim_time: 1.5
  
  # Trajectory Scoring Parameters
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.001
  
  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05