DWAPlannerROS:
  # Robot Configuration
  acc_lim_x: 1.0
  acc_lim_y: 0.0
  acc_lim_theta: 1.0
  max_vel_x: 0.25
  min_vel_x: -0.1
  max_vel_theta: 0.3
  min_vel_theta: -0.3

  # Goal Tolerance
  yaw_goal_tolerance: 6.1
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true
  
  # Forward Simulation
  sim_time: 1.0
  
  # Trajectory Scoring
  path_distance_bias: 90.0
  goal_distance_bias: 50.0
  occdist_scale: 0.001
  
  # Oscillation Prevention
  oscillation_reset_dist: 0.05