DWAPlannerROS:
  # Robot Configuration
  acc_lim_x: 2.0
  acc_lim_y: 0.0
  acc_lim_theta: 4.0
  max_vel_x: 1.0
  min_vel_x: -0.8
  max_vel_theta: 2.5
  min_vel_theta: -2.5

  # Goal Tolerance
  yaw_goal_tolerance: 6.28318530718
  xy_goal_tolerance: 0.3
  
  # Forward Simulation
  sim_time: 2.0
  
  # Trajectory Scoring
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 10.0
  forward_point_distance: 0.6
  
  # Oscillation Prevention
  oscillation_reset_dist: 0.05
  
  publish_cost_grid: true