global_costmap:
  allow_unknown: true
  static_map: true
  global_frame: map
  robot_base_frame: base_footprint
  update_rate: 5.0
  publish_rate: 5.0
  transform_tolerance: 0.5
  plugins:
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}