plants:
  - name: "plant_target_1"
    position: {x: -4.5, y: 4, z: 0.05}
  - name: "plant_target_2"
    position: {x: 0, y: -1, z: 0.05}
  - name: "plant_target_3"
    position: {x: 4, y: -4, z: 0.05}
  - name: "plant_target_4"
    position: {x: 4, y: 4, z: 0.05}

charging_station:
  position: {x: -4.0, y: -4.0, z: 0.0}
