plants:
  - name: "plant_target_1"
    position: {x: -4, y: 4, z: 0}
  - name: "plant_target_2"
    position: {x: -1, y: -1, z: 0}
  - name: "plant_target_3"
    position: {x: 3.5, y: -3.5, z: 0}
  - name: "plant_target_4"
    position: {x: 4, y: 4, z: 0}

charging_station:
  position: {x: -3.0, y: -3.0, z: 0.05}
